# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sync_schema.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'sync_schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sync_schema.proto\".\n\nHistoryLog\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x80\x01\n\rSyncRecordMsg\x12\x12\n\nglobal_oid\x18\x01 \x01(\t\x12\x11\n\trecord_id\x18\x02 \x01(\x05\x12\x10\n\x08metadata\x18\x03 \x01(\t\x12\x13\n\x0btrust_score\x18\x04 \x01(\x02\x12!\n\x0chistory_logs\x18\x05 \x03(\x0b\x32\x0b.HistoryLog\"-\n\nDatasetMsg\x12\x1f\n\x07records\x18\x01 \x03(\x0b\x32\x0e.SyncRecordMsgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sync_schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HISTORYLOG']._serialized_start=21
  _globals['_HISTORYLOG']._serialized_end=67
  _globals['_SYNCRECORDMSG']._serialized_start=70
  _globals['_SYNCRECORDMSG']._serialized_end=198
  _globals['_DATASETMSG']._serialized_start=200
  _globals['_DATASETMSG']._serialized_end=245
# @@protoc_insertion_point(module_scope)
